-- ================================================================
-- FAQ AGENT - EMBEDDINGS TABLE SETUP
-- ================================================================
-- This script sets up the FAQ embeddings table for semantic search.
-- Supports OpenAI text-embedding-3-small (1536 dimensions).
-- ================================================================

-- Enable pgvector extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- ================================================================
-- FAQ EMBEDDINGS TABLE
-- ================================================================

-- Create FAQ embeddings table for semantic search
CREATE TABLE IF NOT EXISTS public.faq_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content TEXT NOT NULL,
    embedding vector(1536),  -- text-embedding-3-small dimensions
    url TEXT NOT NULL,
    title TEXT,
    source_website TEXT,  -- Track which website content came from
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ================================================================
-- INDEXES FOR PERFORMANCE
-- ================================================================

-- HNSW index for fast vector similarity search (cosine distance)
CREATE INDEX IF NOT EXISTS faq_embeddings_embedding_idx 
ON public.faq_embeddings USING hnsw (embedding vector_cosine_ops);

-- URL index for deduplication and lookups
CREATE INDEX IF NOT EXISTS faq_embeddings_url_idx 
ON public.faq_embeddings(url);

-- Created date index for maintenance queries
CREATE INDEX IF NOT EXISTS faq_embeddings_created_at_idx 
ON public.faq_embeddings(created_at DESC);

-- Source website index for filtering by source
CREATE INDEX IF NOT EXISTS faq_embeddings_source_website_idx 
ON public.faq_embeddings(source_website);

-- ================================================================
-- COMMENTS
-- ================================================================

COMMENT ON TABLE public.faq_embeddings IS 'Stores website content chunks with vector embeddings for FAQ semantic search';
COMMENT ON COLUMN public.faq_embeddings.content IS 'Text chunk from scraped website content';
COMMENT ON COLUMN public.faq_embeddings.embedding IS 'Vector embedding generated by OpenAI text-embedding-3-small';
COMMENT ON COLUMN public.faq_embeddings.url IS 'Source URL where this content was scraped from';
COMMENT ON COLUMN public.faq_embeddings.title IS 'Page title or section title';
COMMENT ON COLUMN public.faq_embeddings.source_website IS 'Source website domain (e.g., traguiden.se)';