import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { getOffersData } from '@/lib/offers';

export default async function OffersPage() {
  const offers = getOffersData();

  return (
    <Card>
      <CardHeader>
        <CardTitle>Customer Offers</CardTitle>
        <CardDescription>
          Review and manage offers generated by your AI assistants
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {offers.slice(0, 10).map((offer) => (
            <div
              key={offer.id}
              className="p-4 border border-gray-200 rounded-lg"
            >
              <div className="flex justify-between items-start mb-2">
                <div>
                  <h3 className="font-semibold text-gray-900">
                    {offer.customerInfo.name}
                  </h3>
                  <p className="text-gray-600 text-sm">{offer.customerInfo.email}</p>
                </div>
                <div className="text-right">
                  <div className="text-lg font-bold text-green-600">
                    {offer.offerDetails.totalIncVat.toLocaleString('sv-SE')} kr
                  </div>
                  <div className="text-gray-500 text-xs">
                    {new Date(offer.createdAt).toLocaleDateString('sv-SE')}
                  </div>
                </div>
              </div>
              
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-gray-600 mb-3">
                <div>Area: {offer.offerDetails.area}m²</div>
                <div>Labor: {offer.offerDetails.laborCost.toLocaleString('sv-SE')} kr</div>
                <div>Material: {offer.offerDetails.materialCost.toLocaleString('sv-SE')} kr</div>
                <div>ROT: -{offer.offerDetails.rotDeduction.toLocaleString('sv-SE')} kr</div>
              </div>
              
              <div className="flex flex-wrap gap-1">
                {offer.offerDetails.features.map((feature, idx) => (
                  <span
                    key={idx}
                    className="px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-md"
                  >
                    {feature}
                  </span>
                ))}
              </div>
            </div>
          ))}
          
          {offers.length === 0 && (
            <div className="text-center py-8 text-gray-500">
              No offers generated yet. Start using your AI assistants to see offers here.
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
} 